# Welcome to Jekyll!
#

# Site settings
title: 양윤태 ♥ 서화은
description: |
    blah.....
owner: Hwaeun Seo # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: heseo1013@naver.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yuntae-hwaeun.github.io" # the base hostname & protocol for your site
social:
  instagram: https://instargram.com/heseo89
# Build settings
markdown: kramdown
#sass:
#  style: compressed
